import { Octokit } from '@octokit/rest'

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN })
const owner = process.env.GITHUB_DEPLOY_ORG!

// Create a new GitHub repo and push all generated files to it
export async function createAndPushRepo(
    repoName: string,
    files: Record<string, string>
): Promise<string> {
    // 1. Create the GitHub repository
    await octokit.repos.createForAuthenticatedUser({
        name: repoName,
        private: true,
        description: `Generated by Webjuvelle AI — ${new Date().toISOString()}`,
        auto_init: false,
    })

    // 2. Create an initial commit with all files
    // Get the default branch SHA (it won't exist yet, so we init via blob/tree approach)

    // Create blobs for each file
    const blobs = await Promise.all(
        Object.entries(files).map(async ([path, content]) => {
            const { data } = await octokit.git.createBlob({
                owner,
                repo: repoName,
                content: Buffer.from(content).toString('base64'),
                encoding: 'base64',
            })
            return { path, sha: data.sha }
        })
    )

    // Create a tree from all blobs
    const { data: treeData } = await octokit.git.createTree({
        owner,
        repo: repoName,
        tree: blobs.map(blob => ({
            path: blob.path,
            mode: '100644' as const,
            type: 'blob' as const,
            sha: blob.sha,
        })),
    })

    // Create initial commit
    const { data: commitData } = await octokit.git.createCommit({
        owner,
        repo: repoName,
        message: 'feat: initial Webjuvelle AI-generated website',
        tree: treeData.sha,
        parents: [],
    })

    // Create the main branch and set it as the default
    await octokit.git.createRef({
        owner,
        repo: repoName,
        ref: 'refs/heads/main',
        sha: commitData.sha,
    })

    return `https://github.com/${owner}/${repoName}`
}

// Update files in an existing repo (for revisions)
export async function updateRepoFiles(
    repoName: string,
    updatedFiles: Record<string, string>
): Promise<void> {
    // Get the current main branch SHA
    const { data: ref } = await octokit.git.getRef({
        owner,
        repo: repoName,
        ref: 'heads/main',
    })
    const latestCommitSha = ref.object.sha

    // Get the current tree
    const { data: commit } = await octokit.git.getCommit({
        owner,
        repo: repoName,
        commit_sha: latestCommitSha,
    })

    // Create new blobs for changed files
    const blobs = await Promise.all(
        Object.entries(updatedFiles).map(async ([path, content]) => {
            const { data } = await octokit.git.createBlob({
                owner,
                repo: repoName,
                content: Buffer.from(content).toString('base64'),
                encoding: 'base64',
            })
            return { path, sha: data.sha }
        })
    )

    // Create new tree on top of existing
    const { data: newTree } = await octokit.git.createTree({
        owner,
        repo: repoName,
        base_tree: commit.tree.sha,
        tree: blobs.map(blob => ({
            path: blob.path,
            mode: '100644' as const,
            type: 'blob' as const,
            sha: blob.sha,
        })),
    })

    // Create revision commit
    const { data: newCommit } = await octokit.git.createCommit({
        owner,
        repo: repoName,
        message: 'feat: apply Webjuvelle AI revision',
        tree: newTree.sha,
        parents: [latestCommitSha],
    })

    // Update main branch to point to new commit
    await octokit.git.updateRef({
        owner,
        repo: repoName,
        ref: 'heads/main',
        sha: newCommit.sha,
    })
}
